name: nhentai
description: |
  Powerful client for nhentai.net undocumented APIs, with cookies,
  proxy, full data model and more.
version: 1.0.0-dev.11
homepage: https://github.com/Zekfad/nhentai_dart
repository: https://github.com/Zekfad/nhentai_dart
issue_tracker: https://github.com/Zekfad/nhentai_dart/issues
# documentation: https://pub.dev/documentation/nhentai/latest/

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0
  test: ^1.22.2
  zekfad_lints: ^2.0.0
dependencies: 
  dart_mappable: ^4.3.0
  http: '>=0.13.5 <2.0.0'
  meta: ^1.8.0
